### ISSUE TITLE
BadZipFile issue

### ISSUE THREAD

**Issue by agamemnonc** [cthoyt/drugbank_downloader#2]
Hello, I am trying to use the python code and once the file has downloaded I get a `zipfile.BadZipFile: File is not a zip file` when trying to open it using:
```
with zipfile.ZipFile(path, 'r') as zip_file:
    with zip_file.open("full database.xml") as file:
        pass
```
The file itself is 187 KB, is that its expected size?

**Comment by SneakPeak2003** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by agamemnonc** [comment]
I am wondering whether the answer above is legit?

**Comment by cthoyt** [comment]
This is likely due to you having incorrectly configured/invalid credentials for drugbank. In this case the 403 forbidden page might have been downloaded and saved where the actual file was supposed to be. I’ll try and create a proper error message for this!

**Comment by agamemnonc** [comment]
Thanks for the reply @cthoyt. Just a dumb question, should the credentials be the standard credentials used to login into DrugBank or do I need to set them up differently?

**Comment by cthoyt** [comment]
It’s the regular drugbank username and password

**Comment by cthoyt** [comment]
hi @agamemnonc, I've made an update to get this in. I have to do a bit of packaging updating then will put a new release on PyPI :)

**Comment by cthoyt** [comment]
new version is up! good luck getting your drugbank credentials approved if that's whats blocking you
